#dependens on pywal
include="~/.cache/wal/colors-fuzzel.ini"

font=Iosevka Semibold:size=16
prompt="> "
icons-enabled=no

anchor=center
lines=10
width=40
horizontal-pad=30
vertical-pad=20
inner-pad=5

[border]
width=3
radius=0

[key-bindings]
cancel=Escape Control+g
execute=Return KP_Enter
prev=Control+k
next=Control+j
delete-line-forward=none
